### ISSUE TITLE
error installing wps.

### ISSUE THREAD

**Issue by VaGNaroK** [flathub/com.wps.Office#42] opened 2019-08-24 12:14 UTC
when installing wps today 24/08/19 the following message occurs:

Instalando em system:
com.wps.Office/x86_64/stable flathub aff0a8f4a92e
  permissões: ipc, network, pulseaudio, x11, dri
  acesso a arquivo: /media, /run/media, xdg-documents, xdg-download, xdg-pictures, xdg-videos
  etiquetas: proprietary
Isto está bom [y/n]: y
Instalando: com.wps.Office/x86_64/stable de flathub
[####################] Baixando arquivos: 1899/1899 401,0 MB (1,4 MB/s)         
erro: Falha ao instalar com.wps.Office/x86_64/stable: Tamanho inválido para dados extras http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb

the file "wps-office_11.1.0.8722_amd64.deb" downloads more when it finishes it does not install.

My desktop usage:
https://dpaste.de/nX7d

**Comment by gasinvein** [comment] 2019-08-24 12:17
Duplicate of #40

**Closed by gasinvein** 2019-08-24 12:17 UTC
