### ISSUE TITLE
Fcitx input method is broken with 11.1.0.9615

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.wps.Office#80] opened 2020-09-05 16:47 UTC
I suggest adding `[ "$QT_IM_MODULE" = "fcitx" ] && QT_IM_MODULE=fcitx5` to `/app/extra/wps-office/{et,wpp,wps,wpspdf}`.  
This works for both Fcitx4 and Fcitx5, though only tested a Pinyin method.

**Comment by gasinvein** [comment] 2020-09-22 10:59
Is this a duplicate of #76? Sadly, I know nothing about CJK input in linux.

**Comment by tinywrkb** [comment] 2020-09-22 12:04
I don't think it's related. It's a variant of a known issue and is mentioned in the [Arch Linux wiki page for WPS](https://wiki.archlinux.org/index.php/WPS_Office#Fcitx5_cannot_input_Chinese), though in the Flatpak package case it also affects Fcitx4.  
Note that `QT_IM_MODULE=fcitx` should cover both users of Fcitx4 and Fcitx5 as can be seen with [this commit](https://github.com/fcitx/fcitx5-qt/commit/6fe447439cd4dec0bce825ccfd2059eb35aacf79), there shouldn't be any need to set `QT_IM_MODULE=fcitx5` and this issue might be resolved with a future WPS release if it will also bump its Fcitx5 build (though I couldn't confirm the WPS distributed libqim-fcitx.so is a Fcitx5 module without the debug symbols).

Also note that my current use of Fcitx is pretty limited and that's true also for WPS.

**Comment by gasinvein** [comment] 2020-09-22 12:33
So, is setting `QT_IM_MODULE` to `fcitx5` enough? Does it work if WPS is launched with `flatpak run --env=QT_IM_MODULE=fcitx5 com.wps.Office`?

**Comment by tinywrkb** [comment] 2020-09-22 13:12
Yes and yes, but you can't set this in the Flatpak manifest because it will affect IBus users who are setting `QT_IM_MODULE=ibus` as an environment variable, and this is why I'm suggesting to test `QT_IM_MODULE == fcitx` in the startup script and update the value to `fcitx5` if true.

**Closed** 2021-01-15 17:26 UTC
