### ISSUE TITLE
Failed to install - Error: Wrong size for extra data

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.wps.Office#43] opened 2019-08-27 20:57 UTC
[silverblue@silverblue30 ~]$ flatpak install wps
Looking for matches…
Found similar ref(s) for ‘wps’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.wps.Office/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

com.wps.Office permissions:
    ipc      network              pulseaudio      x11
    dri      file access [1]      tags [2]

    [1] /media, /run/media, xdg-documents, xdg-download, xdg-pictures,
        xdg-videos
    [2] proprietary

        ID                                       Arch            Branch          Op         Remote          Download
 1. [✓] org.freedesktop.Platform.Locale          x86_64          18.08           u          flathub           1.0 kB / 315.9 MB
 2. [✗] com.wps.Office                           x86_64          stable          i          flathub         407.5 MB / 417.7 MB

Error: Wrong size for extra data http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb
error: Failed to install com.wps.Office: Wrong size for extra data http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb
[silverblue@silverblue30 ~]$ flatpak --version
Flatpak 1.2.4

**Comment by gasinvein** [comment] 2019-08-28 09:40
Duplicate of #40

**Closed by gasinvein** 2019-08-28 09:40 UTC
