### ISSUE TITLE
 WPS office cannot save the status of login

### ISSUE THREAD

**Issue by ZILCKIQ** [flathub/com.wps.Office#16] opened 2019-02-24 15:30 UTC
After closing and opening again, I lost the login status of the WPS account.

**Comment by gasinvein** [comment] 2019-02-24 16:18
Is it reproducible?

**Comment by ZILCKIQ** [comment] 2019-02-25 10:00
Every time you log in to a WPS account and close the window and open it again, lose login status.

**Comment by gasinvein** [comment] 2019-02-25 10:18
Since WPS online features are only available with chinese locale, I 
can't test it myself.
Maybe the login data is saved in some directory which is not persistent 
in sandbox (just guessing). Can you please compare contents of the 
transistent home directory before and after login? Run shell inside WPS 
sandbox with `flatpak run --command=bash com.wps.Office`, then `ls -la 
~`, then run WPS itself (`wps`), log in and close it, then run `ls -la 
~` again and compare the output.

**Comment by gasinvein** [comment] 2019-02-25 10:21
Since WPS online features are only available with chinese locale, I can't test it myself.
Maybe the login data is saved in some directory which is not persistent in sandbox (just guessing). Can you please compare contents of the transistent home directory before and after login? Run shell inside WPS sandbox with `flatpak run --command=bash com.wps.Office`, then `ls -la ~`, then run WPS itself (`wps`), log in and close it, then run `ls -la ~` again and compare the output.

**Comment by ZILCKIQ** [comment] 2019-02-26 14:00
There is no difference.
but,
WPS installed in a format other than flatpak will generate".Kingsoft" in the HOME directory and "Kingsoft" in the. local directory. This is not found on the flatpak run -- command = bash com. wps. Office command line running ls -la.

in ".local" directory I found my synchronized cloud file.

My English is not good. This is machine translation. I hope I can express it clearly.

**Comment by gasinvein** [comment] 2019-02-26 14:17
Does running `flatpak run --persist=.kingsoft com.wps.Office` help?

**Comment by ZILCKIQ** [comment] 2019-02-27 20:16
return "QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries."

**Comment by gasinvein** [comment] 2019-03-17 11:50
@ZILCKIQ can you test this https://github.com/flathub/com.wps.Office/pull/20#issuecomment-473657647 build, does if fixes the issue for you?

**Closed** 2019-03-17 12:14 UTC
