### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ivanlechat** [flathub/com.wps.Office#41] opened 2019-08-18 05:06 UTC
Hi there,

I'm getting an error when installing WPS flatpak:

`        ID                 Arch      Branch    Remote     Descarga
 1. [✗] com.wps.Office     x86_64    stable    flathub    259,1 MB / 417,7 MB

Error: Tamaño incorrecto en los datos adicionales http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb
error: Failed to instalar com.wps.Office: Tamaño incorrecto en los datos adicionales http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb`

Can you tell me what can I do to fix it? Any information will be highly appreciated!

Thank you for the great work!

**Comment by ivanlechat** [comment] 2019-08-18 05:11
Thank you for the great work,

I see a similar issue was reported under the "Wrong size for extra data" entry, among the Issues already posted but I'm not sure whether the install issue I'm having is the same or not.

I'm installing it from Colombia, don't know if the location has to do with the Error but, just let me know what I could do to help fix the issue!

Cheers,

**Comment by gasinvein** [comment] 2019-08-18 08:57
Yes, this is duplicate of #40

**Closed by gasinvein** 2019-08-18 08:57 UTC
